# 에러/예외처리

### 1. 디버깅

- branches
  - 모든 조건이 원하는대로 동작하는지
- for loops
  - 반복문에 진입하는지, 원하는 횟수만큼 실행되는지
- while loops
  - for loops와 동일, 종료조건이 제대로 동작하는지
- function
  - 함수 호출시, 파라미터, 결과



### 2. 디버깅 방법

- `print`함수 활용

  - 특정 함수 결과, 반복/조건 결과 등 나눠서 생각

- 개발환경에서 제공하는 기능 활용

  - breakpoint, 변수 조회

- `python tutor`활용

  - 단순 파이썬 코드인 경우
  - [파이썬튜터](https://pythontutor.com/visualize.html#mode=edit)

- 뇌컴파일, 눈디버깅

  

### 3. 에러와 예외

- 문법 에러(Syntax Error)

  - 문법 에러가 발생하면, 파이썬 프로그램은 실행되지 않는다

    - EOL (End of Line)

      ```python
      print('hello
      # 문자열 끝과 괄호를 닫지 않음
      # File "<ipython-input-6-2a5f5c6b1414>", line 1
      # print('hello
      # ^
      # SyntaxError: EOL while scanning string literal
      ```

      

    - EOF  (End of File)

      ```python
      print(
      # 괄호를 닫지 않음
      # File "<ipython-input-4-424fbb3a34c5>", line 1
      # print(
      # ^
      # SyntaxError: unexpected EOF while parsing
      ```

      

    - Invalid Syntax

      ```python
      while
      # 유효하지 않은 문법
      # File "<ipython-input-7-ae84bbebe3ce>", line 1
      # while
      # ^
      # SyntaxError: invalid syntax
      ```

      

    - assign to literal

      ```python
      5 = 3
      # 변수 이름이 숫자로 시작될 때
      # File "<ipython-input-28-9a762f2c796b>", line
      1
      # 5 = 3
      # ^
      # SyntaxError: cannot assign to literal
      ```

      

      



- 예외(Exception)

  - 실행 도중 예상치 못한 상황에 프로그램 실행을 멈춤

  - 실행 중 감지되는 에러들을 예외라고 함

  - 여러 타입으로 나타나고, 일부 출력됨

  - 모든 내장 예외는 Exception Class를 상속받아 이뤄짐

  - 사용자 정의 예외를 만들어 관리할 수 있다

    - ZeroDivisionError

      ```python
      10/0
      # 0으로 나눌 수 없다
      # ---------------
      # ZeroDivisionError Traceback (most recent call last)
      # ----> 1 10/0
      # ZeroDivisionError: division by zero
      ```

      

    - NameError

      ```python
      print(name_error)
      # 참조 변수가 없다
      # ---------------------------
      # NameError Traceback (most recent call last)
      # ----> 1 print(name_error)
      # NameError: name 'name_error' is not defined
      
      name_error = 10
      print(name_error)
      ```
    
      
    
    - TypeError
    
      ```python
      1 + '1'
      # 타입 불일치
      # --------------
      # TypeError Traceback (most recent call last)
      # ----> 1 1 + '1'
      # TypeError: unsupported operand type(s) for +: 'int' and 'str'
      ```
    
      ```python
      divmod()
      # arguments 부족
      # ------------
      # TypeError Traceback (most recent call last)
      # ----> 1 divmod()
      # TypeError: divmod expected 2 arguments, got 0
      ```
    
      ```python
      import random
      random.sample()
      # argument 부족
      # ---------
      # TypeError Traceback (most recent call last)
      # 1 import random
      # ----> 2 random.sample()
      # TypeError: sample() missing 2 required positional arguments:
      'population' and 'k
      ```
    
      ```python
      import random
      random.sample(range(3), 1, 2)
      # argument 초과
      # --------
      # TypeError Traceback (most recent call last)
      # 1 import random
      # ----> 2 random.sample(range(3), 1, 2)
      # TypeError: sample() takes 3 positional arguments but 4 were given
      ```
    
    
    
    
    - ValueError
    
      ```python
      int('3.5')
      # 타입은 올바르나, 값이 부적절
      # ------
      # ValueError Traceback (most recent call last)
      # ----> 1 int('3.5')
      # ValueError: i
      ```
    
    
    
    
    - IndexError
    
      ```python
      empty_list = []
      empty_list[2]
      # 인덱스 범위를 벗어남
      # ------
      # IndexError Traceback (most recent call last)
      # 1 empty_list = []
      # ----> 2 empty_list[2]
      # IndexError: list index out of range
      ```

      
    
    - KeyError
    
      ```python
      song = {'IU': '좋은날'}
      song['BTS']
      # 키 없음
      # ------
      # KeyError Traceback (most recent call last)
      # 1 song = {'IU': '좋은날'}
      # ----> 2 song['BTS']
      # KeyError: 'BTS'
      ```
    
      
    
    - ModuleNotFound
    
      ```python
      import nonamed
      # 존재하지 않는 모듈을 import하는 경우
      # ------
      # ModuleNotFoundError Traceback (most recent call last)
      # ----> 1 import nonamed
      # ModuleNotFoundError: No module named 'nonamed'
      ```
    
      
    
    - ImportError
    
      ```python
      from random import samp
      # module은 있으나 존재하지 않는 클래스나 함수를 가져오는 경우
      # ------
      # ImportError Traceback (most recent call last)
      # ----> 1 from random import samp
      # ImportError: cannot import name 'samp' from 'random'
      ```
    
      
    
    - IndentationError
    
      ```python
      for i in range(3):
      print(i)
      # 들여쓰기가 적절하지 않은 경우
      # File "<ipython-input-56-78291925d94f>", line 2
      # print(i)
      # ^
      # IndentationError: expected an indented block
      ```
    
      
    
    - KeyboardInterupt
    
      ```python
      while True:
      continue
      # 임의로 프로그램을 종료했을 때
      # ------
      # KeyboardInterrupt Traceback (most recent call last)
      # <ipython-input-55-6a65cf439648> in <module>
      # 1 while True:
      # ----> 2 continue
      # KeyboardInterrupt: 
      ```
    
      

- [파이썬 내장 예외](https://docs.python.org/ko/3/library/exceptions.html#exception-hierarchy)



### 4. 예외처리

- `try`, `except`를 이용해 예외처리 가능

- try

  - 오류가 발생할 가능성이 있는 코드를 실행
  - 예외가 발생되지 않으면, except 없이 실행 종료

- except

  - 예외가 발생하면, except 실행

  - 예외 상황을 처리하는 코드를 받아서 적절한 조치를 취함

    ```python
    try:
      명령문 # try문은 반드시 한 개 이상의 except 필요
    except 예외그룹-1 as 변수-1:
      명령문
    except 예외그룹-2 as 변수-2:
      명령문
    finally: # 선택사항
      명령문
    ```
  
- 예시
    ```python
    #1
    num = input('숫자입력 :')
    print(int(num))
    # 숫자입력 :3
    # 3
    ======================================================================
    num = input('숫자입력 :')
    print(int(num))
    # 숫자입력 :안녕
    # ------
    # ValueError Traceback (most recent call last)
    # 1 num = input('숫자입력 :')
    # ----> 2 print(int(num))
    # ValueError: invalid literal for int() with
    base 10: '안녕
    ```
    
    ```python
    try:
      num = input('숫자 입력 : ')
      print(int(num))
    except:
      print('숫자가 아닙니다.')
    ```
    
    ```python
    #2
    num = input('100으로 나눌 값을 입력하시오 : ')
    print(100/int(num))
    ```
    
    ```python
    # 복수의 예외처리
    try:
    num = input('100으로 나눌 값을 입력하시오: ')
    100/int(num)
    except (ValueError, ZeroDivisionError): # 발생 가능한 에러
    print('제대로 입력해줘')
    ======================================================================
    try:
    num = input('값을 입력하시오: ')
    100/int(num)
    except ValueError:
    print('숫자를 넣어주세요.')
    except ZeroDivisionError:
    print('0으로 나눌 수 없습니다.')
    except:
    print('에러는 모르지만 에러가 발생하였습니다.')
    ```